spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
