spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_PASS:dev} # 获取不到就取默认值dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${PORT:8082}
